version: '3'
services:
    redis:
        image: redis
        expose:
         - 6379
        # ports:
        #  - "127.0.0.2:6379:6379"
    web:
        image: game-demo
        links:
         - redis
        ports:
         - "127.0.0.1:5000:5000"